#!/bin/bash
echo "=== Verifying stack_coroutine ==="
echo ""
echo "1. Running tests..."
cargo test --target riscv64gc-unknown-linux-gnu --lib 2>&1 | grep -E "(test result|running)"
echo ""
echo "2. Checking for warnings..."
cargo test --target riscv64gc-unknown-linux-gnu --lib 2>&1 | grep -i warning || echo "No warnings found"
echo ""
echo "3. Verifying key functions exist..."
grep -q "pub unsafe fn switch_context" src/lib.rs && echo "✓ switch_context function exists"
grep -q "pub fn alloc_stack" src/lib.rs && echo "✓ alloc_stack function exists"
grep -q "pub fn init" src/lib.rs && echo "✓ init function exists"
echo ""
echo "4. All tests passed!"
